### ISSUE TITLE
Reprducing results on fr3_household

### ISSUE THREAD

**Issue by theNded** [martinruenz/maskfusion#35]
Hi, thanks for the open source project.

It seems that we cannot reproduce results on the tum fr3_household dataset with the default parameters. Using less strict thresholds can give us a reasonable trajectory without object tracking module, but nothing seems to work with object tracking module turned on. 

Would you like to kindly share the parameter you were using for this sequence for your ISMAR paper? Thanks.

**Comment by martinruenz** [comment]
Hi,
Thanks for your interest in MaskFusion. It’s been quite a while since running the experiments and I don’t have records of the exact experiment configurations. However, I believe we pretty much used the default config. One thing to consider is that we used a hacky hand-detection for moving objects in order to reduce false positive object detections.
Which exact sequence are you referring to? We didn’t actually perform experiments on `fr3_household`. 
Do you observe frame-drops / is the frame-rate high enough? A low frame-rate affects the tracking performance and leads to worse results.

**Comment by theNded** [comment]
Thanks for the reply!

Sorry for the confusion, we were evaluating the fr3/long_office_household sequence. Fig. 6 in the paper depicted the trajectory of this scene.

We didn't use manual detection, I guess that could be the major reason that tracking failed -- we detected 24 objects in total (including backgrounds), and many were false duplicates. I think we may try to fix teddy and see what happens.

We first used the offline_runner to generate the masks, and ran in the offline mode provided depth and color, so framerate would not be an issue.
